# Edited: 29.10 13:25

devices = [
	{
		"id": 1,
		"name": "Lights Hall",
		"ip": "192.168.1.145",
		"state": 0,
		"device_key": "dfj7sdf40dg",
		"typeId": 1,
		"command": "lights_hall",
		"description": "Turns on/off hall lights"
	},
	{
		"id": 2,
		"name": "Lights Kitchen",
		"ip": "192.168.1.101",
		"state": 0,
		"device_key": "a45bcKewefEfd",
		"typeId": 1,
		"command": "lights_kitchen",
		"description": "Turns on/off kitchen lights"
	},
	{
		"id": 3,
		"name": "Lights Main Room",
		"ip": "192.168.1.102",
		"state": 0,
		"device_key": "24t346g5y88732Efd",
		"typeId": 1,
		"command": "lights_main",
		"description": "Turns on/off Main Room lights"
	},
	{
		"id": 4,
		"name": "Lights Bedroom",
		"ip": "192.168.1.211",
		"state": 0,
		"device_key": "abcKey88732Efd",
		"typeId": 1,
		"command": "lights_bedroom",
		"description": "Turns on/off bedroom lights"
	},
	{
		"id": 5,
		"name": "Lights Bedroom2",
		"ip": "192.168.1.212",
		"state": 0,
		"device_key": "a4i827i3732E45",
		"typeId": 1,
		"command": "lights_bedroom2",
		"description": "Turns on/off bedroom2 lights"
	},
	{
		"id": 6,
		"name": "Lights Bedroom3",
		"ip": "192.168.1.213",
		"state": 0,
		"device_key": "MHD57odcio732Efd",
		"typeId": 1,
		"command": "lights_bedroom3",
		"description": "Turns on/off bedroom3 lights"
	},
	{
		"id": 7,
		"name": "Lights Bedroom4",
		"ip": "192.168.1.215",
		"state": 0,
		"device_key": "mdc03knb8873i3m",
		"typeId": 1,
		"command": "lights_bedroom4",
		"description": "Turns on/off bedroom4 lights"
	},
	{
		"id": 8,
		"name": "Curtain",
		"ip": "192.168.1.123",
		"state": 0,
		"device_key": "sqs20n7nI9mdio2mew",
		"typeId": 1,
		"command": "curtain",
		"description": "Moves up and down the curtain"
	},
	{
		"id": 9,
		"name": "Smart conditioner",
		"ip": "192.168.1.243",
		"state": 0,
		"device_key": "conD9mdc73om934",
		"typeId": 2,
		"command": "conditioner_main",
		"description": "Controls conditioner"
	},
	{
		"id": 10,
		"name": "ESP-01 Smart Socket",
		"ip": "192.168.1.144",
		"state": 0,
		"device_key": "knb78G^n03foi",
		"typeId": 2,
		"command": "socket",
		"description": "Controls Smart socket"
	},
	{
		"id": 11,
		"name": "Smart conditioner1",
		"ip": "192.168.1.244",
		"state": 0,
		"device_key": "conD9mmg#$dc73om934",
		"typeId": 2,
		"command": "conditioner_main2",
		"description": "Controls conditioner"
	},
	{
		"id": 12,
		"name": "Smartconditioner2",
		"ip": "192.168.1.245",
		"state": 0,
		"device_key": "conD9mheqdc73om934",
		"typeId": 2,
		"command": "conditioner_kitchen",
		"description": "Controls conditioner"
	},
	{
		"id": 13,
		"name": "Smart conditioner3",
		"ip": "192.168.1.246",
		"state": 0,
		"device_key": "C6conD9mheqdc73om934q",
		"typeId": 2,
		"command": "conditioner_bed",
		"description": "Controls conditioner"
	},
	{
		"id": 14,
		"name": "Smart conditioner4",
		"ip": "192.168.1.248",
		"state": 0,
		"device_key": "C$@onD9mheqdc73om934q!",
		"typeId": 2,
		"command": "conditioner_bed3",
		"description": "Controls conditioner"
	},
	{
		"id": 15,
		"name": "Smart conditioner5",
		"ip": "192.168.1.249",
		"state": 0,
		"device_key": "C$@onD9mheqdc73om%&934q!",
		"typeId": 2,
		"command": "conditioner_bed3",
		"description": "Controls conditioner"
	},
	{
		"id": 16,
		"name": "Smart conditioner6",
		"ip": "192.168.1.250",
		"state": 0,
		"device_key": "shunyhembelle",
		"typeId": 2,
		"command": "conditioner_bed4",
		"description": "Controls conditioner"
	},
	{
		"id": 17,
		"name": "Curtain",
		"ip": "192.168.1.119",
		"state": 0,
		"device_key": "zalyuz25gowy",
		"typeId": 1,
		"command": "main_curtain",
		"description": "Moves up and down the curtain"
	},
	{
		"id": 18,
		"name": "Suwsensor",
		"ip": "192.168.1.130",
		"state": 0,
		"device_key": "dfj7sdsegf40dg",
		"typeId": 1,
		"command": "suwsensor",
		"description": "Turns on/off hall lights"
	},
	{
		"id": 19,
		"name": "Suwsensor1",
		"ip": "192.168.1.131",
		"state": 0,
		"device_key": "Qsd2dfj7sdsegf40dg",
		"typeId": 1,
		"command": "suwsensorBanya",
		"description": "Turns on/off hall lights"
	},
	{
		"id": 20,
		"name": "Suwsensor1",
		"ip": "192.168.1.132",
		"state": 0,
		"device_key": "Qsd2dgwqzdsegf40dg",
		"typeId": 1,
		"command": "suwsensorBanya",
		"description": "Turns on/off hall lights"
	},
	{
		"id": 21,
		"name": "Smart stove",
		"ip": "192.168.1.154",
		"state": 0,
		"device_key": "knb78G^n0sdf3foi",
		"typeId": 2,
		"command": "smart_stove",
		"description": "Controls stove"
	},
	{
		"id": 22,
		"name": "IoT TV Remote",
		"ip": "192.168.1.176",
		"state": 0,
		"device_key": "asdgdsf4567)N$3zx4a2",
		"typeId": 2,
		"command": "tv_remote",
		"description": "Controls Remote of smart tv that sends IR datas"
	},
	{
		"id": 23,
		"name": "Watt measurer of kitchen",
		"ip": "192.168.1.222",
		"state": 0,
		"device_key": "jbhbnefb63bno2u1",
		"typeId": 2,
		"command": "watt_measurer1",
		"description": "Measures the flow of current"
	},
	{
		"id": 24,
		"name": "Water measurer of kitchen",
		"ip": "192.168.1.223",
		"state": 0,
		"device_key": "jbhbnefb63bno2u1",
		"typeId": 2,
		"command": "water_measurer1",
		"description": "Measures the flow of water"
	},
	{
		"name": "Local binary test",
		"ip": "127.0.0.1:5000",
		"state": 0,
		"device_key": "23abcK238873244",
		"typeId": 1,
		"command": "test_local",
		"description": "Turns on/off Local test"
	},
	{
		"id": 999,
		"name": "Local Json to Args test",
		"ip": "127.0.0.1:5000",
		"state": 0,
		"device_key": "ase44f3f23f3",
		"typeId": 2,
		"command": "test_local_json",
		"description": "Json to args of local test func"
	}
]

pins = [
	{
		"id": 1,
		"name": "Socket1",
		"command": "socket1",
		"description": "Pin 2 of smart socket",
		"action": "0",
		"deviceId": 10,
	},
	{
		"id": 2,
		"name": "Socket2",
		"command": "socket2",
		"description": "Pin 2 of smart socket",
		"action": "0",
		"deviceId": 10,
	},
	{
		"id": 3,
		"name": "Socket3",
		"command": "socket3",
		"description": "Pin3 of smart socket",
		"action": "0",
		"deviceId": 10,
	},
	{
		"id": 4,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 9,
	},
	{
		"id": 5,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 9,
	},
	{
		"id": 6,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 9,
	},
	{
		"id": 7,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 9,
	},
	{
		"id": 8,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 9,
	},
	{
		"id": 9,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 11,
	},
	{
		"id": 10,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 11,
	},
	{
		"id": 11,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 11,
	},
	{
		"id": 12,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 11,
	},
	{
		"id": 13,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 11,
	},
	{
		"id": 14,
		"name": "Cooker heater 1",
		"command": "cooker1",
		"description": "Controls the cooker heaters timing.",
		"action": "0",
		"deviceId": 21,
	},
	{
		"id": 15,
		"name": "Cooker heater 2",
		"command": "cooker2",
		"description": "Controls the cooker heaters timing.",
		"action": "0",
		"deviceId": 21,
	},
	{
		"id": 16,
		"name": "Cooker heater 3",
		"command": "cooker3",
		"description": "Controls the cooker heaters timing.",
		"action": "0",
		"deviceId": 21,
	},
	{
		"id": 17,
		"name": "Cooker heater 4",
		"command": "cooker4",
		"description": "Controls the cooker heaters timing.",
		"action": "0",
		"deviceId": 21,
	},
	{
		"id": 18,
		"name": "Cooker power pin",
		"command": "power",
		"description": "Controls the cooker power source.",
		"action": "0",
		"deviceId": 21,
	},
	{
		"id": 19,
		"name": "Cooker Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 21,
	},
	{
		"id": 42,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 12,
	},
	{
		"id": 52,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 12,
	},
	{
		"id": 62,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 12,
	},
	{
		"id": 72,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 12,
	},
	{
		"id": 82,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 12,
	},
	{
		"id": 43,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 13,
	},
	{
		"id": 53,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 13,
	},
	{
		"id": 63,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 13,
	},
	{
		"id": 73,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 13,
	},
	{
		"id": 83,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 13,
	},
	{
		"id": 44,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 14,
	},
	{
		"id": 54,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 14,
	},
	{
		"id": 64,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 14,
	},
	{
		"id": 74,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 14,
	},
	{
		"id": 84,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 14,
	},
	{
		"id": 45,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 15,
	},
	{
		"id": 55,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 15,
	},
	{
		"id": 65,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 15,
	},
	{
		"id": 75,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 15,
	},
	{
		"id": 85,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 15,
	},
	{
		"id": 46,
		"name": "Conditioner Mode HIGH",
		"command": "mode_high",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 16,
	},
	{
		"id": 56,
		"name": "Conditioner Mode MED",
		"command": "mode_med",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 16,
	},
	{
		"id": 66,
		"name": "Conditioner Mode LOW",
		"command": "mode_low",
		"description": "Changes the conditioner operation power",
		"action": "0",
		"deviceId": 16,
	},
	{
		"id": 76,
		"name": "Conditioner Auto/Manual switch",
		"command": "auto_manual_switch",
		"description": "Changes the use of manual or auto mode (Tel mode)",
		"action": "auto",
		"deviceId": 16,
	},
	{
		"id": 86,
		"name": "Temperature control",
		"command": "temperature",
		"description": "Controls room temperature according to command (ex.: 'heater:25:' or 'cooler:16:')",
		"action": "cooler:20:",
		"deviceId": 16,
	},
	{
		"id": 87,
		"name": "IR Remote command",
		"command": "command",
		"description": "sends the command to arduino to manage TV",
		"action": "tvpower",
		"deviceId": 22,
	},
	{
		"id": 998,
		"name": "Mirror switch",
		"command": "switch_mirror",
		"description": "Mirror actuator pin",
		"action": "0",
		"deviceId": 999,
	},
	{
		"id": 999,
		"name": "AI pin",
		"command": "switch_AI",
		"description": "Activates AI function",
		"action": "0",
		"deviceId": 999,
	}
]

device_types = [
	{
		"id": 1,
		"name": "ESP-01-binary",
		"description": "ESP8266 Binary data like '/control/1' or '/control/0'"
	},
	{
		"id": 2,
		"name": "ESP-JSON-to-Arguments",
		"description": "ESP8266 with several arguments provided from data in JSON"
	},
	{
		"id": 3,
		"name": "Esp8266-command-argument",
		"description": "ESP8266 with argument provided in 'control' from data in 'action' of JSON"
	}
]


sensors = [
	{
		"id": 1,
		"name": "Watt measurer sensor",
		"command": "watt_measurer",
		"description": "Measured amount of current",
		"value": "0.0",
		"deviceId": 23,
	},
	{
		"id": 2,
		"name": "Water measurer sensor",
		"command": "water_measurer",
		"description": "Measured amount of water",
		"value": "0.0",
		"deviceId": 24,
	}
]